# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

def getVersionCode
  # Instead of managing the version code manually it is simply based on a timestamp in sec
  # Any build done more recently is considered to be a higher version
  # versionCode increase every minute (aka max 1 build per minute)
  # versionCode can't be smaller than legacyVersionCode
  thirtySeptemberTwentyTwenty = 1601480940 / 60
  legacyVersionCode = 10902
  versionCode = legacyVersionCode + (Time.now.to_i / 60) - thirtySeptemberTwentyTwenty

  if versionCode > 2100000000
    raise "versionCode cannot be higher than 2100000000"
  end

  versionCode.floor()
end

platform :android do
	desc "Increments internal build number tracking (different than version)"
    lane :bump_build_number do
      android_set_version_code(
        version_code: getVersionCode(),
        gradle_file: "./android/app/build.gradle"
      )
  end

  desc "Build and uploads the app to playstore for a internal testing release"
  lane :playstoreInternal do |options|
		# Retrieve version of my app in package.json (React Native case)
    package = load_json(json_path: "./package.json")

		# Clean build folder
    gradle(
      task: "clean",
      project_dir: 'android/'
    )

		# Bump android.defaultConfig.versionCode
    bump_build_number

		# Do the bundle of the application
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android/',
      properties: {
        "android.injected.signing.store.file" => Dir.pwd + "/release.keystore",
        "android.injected.signing.store.password" => options[:RELEASE_KEYSTORE_PASSWORD], # keystore password
        "android.injected.signing.key.alias" => options[:RELEASE_KEYSTORE_ALIAS], # alias
        "android.injected.signing.key.password" => options[:RELEASE_KEYSTORE_KEY_PASSWORD], # key password
        "vname" => package["version"]
      }
    )

		# Upload Android App Bundle to PlayStore like Internal testing Release
    # upload_to_play_store(
    #   track: 'internal',
    #   skip_upload_apk: true,
    #   version_name: package["version"]
    # )
  end
end
