name: Push to internal testing
on:
  push:
    branches:
      - develop

jobs:
  Build-and-Deploy:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.SERVICE_ACCOUNT_PASSPHRASE }}

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Install packages
        run: |
          npm i

      - name: Run tests
        run: |
          npm run test

      - name: Upload to PlayStore
        run: |
          bundle install
          bundle exec fastlane android playstoreInternal RELEASE_KEYSTORE_PASSWORD:${{secrets.RELEASE_KEYSTORE_PASSWORD}} RELEASE_KEYSTORE_KEY_PASSWORD:${{secrets.RELEASE_KEYSTORE_KEY_PASSWORD}} RELEASE_KEYSTORE_ALIAS:${{secrets.RELEASE_KEYSTORE_ALIAS}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            android/app/build/outputs/bundle/release/
